# Match the base images the Supervisor uses when building on-device (Alpine).
# Custom base (e.g. python:3.11-slim) would only apply when building via CI/builder.
build_from:
  armhf: ghcr.io/home-assistant/armhf-base:latest
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
  i386: ghcr.io/home-assistant/i386-base:latest
